openapi: 3.0.1
info:
  title: myfitnessapp-server
  description: My Fitness App Server
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Programs
    description: Exercise programs endpoints
  - name: Specification
    description: The swagger API specification
paths:
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
  /programs:
    get:
      tags:
        - Exercise Programs
      description: Fetch all examples
      responses:
        200:
          description: Returns all exercise programs
          content: {}
  /exercises:
    post:
      tags:
        - Exercises
      description: Add a new exercise
      requestBody:
        description: an exercise
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExerciseBody'
        required: true
      responses:
        200:
          description: Returns the newly created exercise
          content: {}
  /exercises/{id}:
    get:
      tags:
        - Exercises
      parameters:
        - name: id
          in: path
          description: The id of the example to retrieve
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Return the example with the specified id
          content: {}
        404:
          description: Example not found
          content: {}

components:
  schemas:
    ExerciseBody:
      title: exercise
      required:
        - name
      type: object
      properties:
        name:
          type: string
          example: pull-ups
        description:
          type: string
          example: back exercise that targets lats
